-- SYNTHESIS PLATFORM - DEFINITIVE MASTER SETUP
-- PURPOSE: Clean start for Login, Signup, and Social Auth
-- RUN THIS SCRIPT TO RESET EVERY AUTH CONFLICT

-- ==========================================
-- 1. AUTHENTICATION INFRASTRUCTURE
-- ==========================================
DROP DATABASE IF EXISTS auth_platform;
CREATE DATABASE auth_platform;
USE auth_platform;

-- Create Unified Users Table
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    auth_provider VARCHAR(50) DEFAULT 'LOCAL',
    provider_id VARCHAR(255) DEFAULT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create Unified Roles Table
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50),
    CONSTRAINT fk_auth_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Initialize Master Admin (LOCAL)
-- Username: admin | Password: admin123
INSERT INTO users (username, email, password, full_name, auth_provider)
VALUES ('admin', 'admin@synthetic.ai', 'admin123', 'System Administrator', 'LOCAL');

INSERT INTO user_roles (user_id, role) 
VALUES (LAST_INSERT_ID(), 'ROLE_ADMIN'), (LAST_INSERT_ID(), 'ROLE_USER');


-- ==========================================
-- 2. CORE ENGINE INFRASTRUCTURE
-- ==========================================
DROP DATABASE IF EXISTS synthetic_platform;
CREATE DATABASE synthetic_platform;
USE synthetic_platform;

-- (Tables for Projects, Datasets, and Models will be auto-generated by Hibernate)

-- ==========================================
-- 3. FINAL VERIFICATION
-- ==========================================
SHOW DATABASES;
SELECT * FROM auth_platform.users;
